# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitpod.Dockerfile'
      - '.gitpod.yml'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitpod.Dockerfile'
      - '.gitpod.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Use Node.js
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm dedupe --dry-run
      - uses: nick-fields/retry@v3.0.0
        with:
          timeout_minutes: 2
          max_attempts: 3
          retry_on: error
          command: npm ci
      - run: ESLINT_USE_FLAT_CONFIG=false npx eslint src
      - uses: nick-fields/retry@v3.0.0
        with:
          timeout_minutes: 2
          max_attempts: 2
          retry_on: error
          command: npx playwright install --with-deps
      - name: run tests
        uses: nick-fields/retry@v3.0.0
        with:
          timeout_minutes: 3
          max_attempts: 3
          retry_on: error
          command: npm run test
      - uses: actions/upload-artifact@v4.4.1
        with:
          name: build-for-${{github.sha}}
          path: |
            dist/
